### ISSUE TITLE
Good shortname for this alg/space

### ISSUE THREAD

**Issue by s5bug** [nschloe/note-on-cam16#2]
In a color library, should this space be called `CAM16`, fully replacing the original CIE definition, or should both coexist, with this version called something else? If the latter, what would a good shortname be?

**Comment by nschloe** [comment]
It's the same algorithm, but there are algorithmic improvements. In infinite precision, the results are the same, but on a computer, this algorithm here is both more robust, less complex, and (slightly) faster. I wouldn't give it a different name, but perhaps call it _Schlömer's variant of CAM16_ or something like that.

**Comment by s5bug** [comment]
Sounds good. It'll probably be just `CAM16`, then (the documentation will link to your paper though).
